/**
 * Brand assets for the docs, all derived: KCQ design tokens from the pinned chart (the same
 * generator the public pages use), the subset font files the public pages ship, and the
 * KLineChartQuant wordmark as vector outlines of Outfit 600 (ADR 0001), so no display font loads.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import opentype from "opentype.js";
import { buildTokensCss } from "../../../kcq/scripts/landing-source.mjs";
import { glyphPath } from "../../../kcq/src/public/brand/glyph.ts";
import { APP_ROOT, KCQ_APP_ROOT } from "./source.mjs";

const require = createRequire(resolve(APP_ROOT, "package.json"));

export function tokensCss(source) {
  return buildTokensCss(source);
}

/** Subset fonts the public pages already ship (apps/kcq/src/public/brand). */
const FONTS = [
  {
    file: "kcq-dm-sans-500.woff2",
    name: "dm-sans-500",
    family: "DM Sans",
    weight: "500",
    preload: true,
  },
  {
    file: "kcq-geist-latin.woff2",
    name: "geist-latin",
    family: "Geist",
    weight: "400 600",
    preload: true,
  },
  {
    file: "kcq-geist-mono-latin.woff2",
    name: "geist-mono-latin",
    family: "Geist Mono",
    weight: "400",
    preload: false,
  },
];

/** Metric fallbacks measured against Arial / Courier New (the public pages' values). */
const FALLBACKS = `@font-face {
  font-family: "DM Sans Fallback";
  src: local("Arial"), local("ArialMT");
  size-adjust: 106.22%;
  ascent-override: 93.39%;
  descent-override: 29.18%;
  line-gap-override: 0%;
}
@font-face {
  font-family: "Geist Fallback";
  src: local("Arial"), local("ArialMT");
  size-adjust: 105.15%;
  ascent-override: 95.57%;
  descent-override: 28.05%;
  line-gap-override: 0%;
}
@font-face {
  font-family: "Geist Mono Fallback";
  src: local("Courier New"), local("CourierNewPSMT");
  size-adjust: 99.98%;
  ascent-override: 100.52%;
  descent-override: 29.5%;
  line-gap-override: 0%;
}
`;

/**
 * Copy the fonts under content-hashed names (nginx serves woff2 as immutable for a year) and
 * return the @font-face CSS plus the preload list.
 */
export function copyFonts(targetDir) {
  mkdirSync(targetDir, { recursive: true });
  for (const stale of readdirSync(targetDir)) rmSync(resolve(targetDir, stale), { force: true });
  const faces = [];
  const preload = [];
  for (const font of FONTS) {
    const bytes = readFileSync(resolve(KCQ_APP_ROOT, "src/public/brand", font.file));
    const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 10);
    const name = `${font.name}.${hash}.woff2`;
    writeFileSync(resolve(targetDir, name), bytes);
    const url = `/docs/fonts/${name}`;
    faces.push(
      `@font-face {\n  font-family: "${font.family}";\n  src: url("${url}") format("woff2");\n  font-weight: ${font.weight};\n  font-style: normal;\n  font-display: swap;\n}`,
    );
    if (font.preload) preload.push(url);
  }
  return {
    css: `/* Generated by scripts/lib/brand.mjs. */\n${faces.join("\n")}\n${FALLBACKS}`,
    preload,
  };
}

function parseFont(file) {
  const buffer = readFileSync(file);
  return opentype.parse(
    buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength),
  );
}

export function outfitFont() {
  return parseFont(require.resolve("@fontsource/outfit/files/outfit-latin-600-normal.woff"));
}

/**
 * SVG path data from opentype commands. opentype.js 2's own toPathData emits NaN for some
 * quadratic control points (seen with Geist and Noto Sans SC), so serialize the commands directly.
 */
export function pathData(path) {
  const n = (v) => {
    if (!Number.isFinite(v)) throw new Error("Non-finite glyph coordinate");
    return String(Math.round(v * 100) / 100);
  };
  return path.commands
    .map((c) => {
      if (c.type === "M" || c.type === "L") return `${c.type}${n(c.x)} ${n(c.y)}`;
      if (c.type === "Q") return `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`;
      if (c.type === "C") return `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`;
      return "Z";
    })
    .join("");
}

/** `KLineChartQuant` outlined at 16px with the public pages' -0.02em tracking. */
export function wordmark() {
  const font = outfitFont();
  const size = 16;
  const tracking = -0.02 * size;
  let x = 0;
  const path = new opentype.Path();
  for (const char of "KLineChartQuant") {
    const glyph = font.charToGlyph(char);
    path.extend(glyph.getPath(x, 0, size));
    x += (glyph.advanceWidth / font.unitsPerEm) * size + tracking;
  }
  const box = path.getBoundingBox();
  const capHeight = ((font.tables.os2?.sCapHeight ?? 700) / font.unitsPerEm) * size;
  const round = (n) => Math.round(n * 100) / 100;
  // The box keeps Q's tail; `capHeight` lets the component align the caps to the text centre.
  return {
    glyph: glyphPath(),
    d: pathData(path),
    viewBox: `${round(box.x1)} ${round(box.y1)} ${round(box.x2 - box.x1)} ${round(box.y2 - box.y1)}`,
    width: round(box.x2 - box.x1),
    height: round(box.y2 - box.y1),
    capHeight: round(capHeight),
    descent: round(box.y2),
  };
}
