// GENERATED by scripts/gen-catalog-fonts.mjs — do not edit.
//
// One next/font/google call per typeface the catalog names and Google carries.
// Each downloads at build time and is served from this origin, so a specimen
// renders in its own face with no runtime request to Google and no CSP change.
//
// 120 of 128 faces load; the rest are listed as unavailable.

import {
  Abel,
  Akshar,
  Alfa_Slab_One,
  Allura,
  Amatic_SC,
  Amiko,
  Anton,
  Arsenal,
  Arvo,
  Asul,
  Averia_Serif_Libre,
  Balthazar,
  Bebas_Neue,
  Beth_Ellen,
  BioRhyme,
  Bitter,
  Black_Han_Sans,
  Cabin,
  Cherry_Swash,
  Cormorant,
  Courier_Prime,
  Cousine,
  Coustard,
  Covered_By_Your_Grace,
  Crimson_Pro,
  Crimson_Text,
  Dancing_Script,
  DM_Sans,
  Domine,
  Dosis,
  EB_Garamond,
  Fjalla_One,
  Frank_Ruhl_Libre,
  Fraunces,
  Funnel_Display,
  Funnel_Sans,
  Fustat,
  Gantari,
  Geist,
  Geist_Mono,
  Geologica,
  Germania_One,
  Gilda_Display,
  Glegoo,
  Gloock,
  Hina_Mincho,
  IBM_Plex_Sans,
  Inclusive_Sans,
  Instrument_Sans,
  Instrument_Serif,
  Inter,
  Josefin_Sans,
  Jost,
  Karla,
  Kiwi_Maru,
  Lato,
  Libre_Caslon_Display,
  Libre_Caslon_Text,
  Lobster,
  Lora,
  Madimi_One,
  Manrope,
  Martian_Mono,
  Merriweather_Sans,
  Metamorphous,
  Michroma,
  Miriam_Libre,
  Montserrat,
  Newsreader,
  Noto_Nastaliq_Urdu,
  Noto_Sans,
  Noto_Sans_Arabic,
  Noto_Sans_Egyptian_Hieroglyphs,
  Noto_Sans_Limbu,
  Noto_Sans_Mono,
  Noto_Sans_SC,
  Noto_Sans_Symbols,
  Noto_Sans_Vai,
  Noto_Sans_Warang_Citi,
  Noto_Serif,
  Noto_Serif_SC,
  Noto_Serif_Tibetan,
  Nova_Slim,
  Nunito,
  Nunito_Sans,
  Ojuju,
  Old_Standard_TT,
  Orbitron,
  Outfit,
  Ovo,
  Pacifico,
  Parkinsans,
  Pinyon_Script,
  Playfair_Display,
  Plus_Jakarta_Sans,
  Prompt,
  Public_Sans,
  Quattrocento,
  Roboto,
  Roboto_Condensed,
  Rubik,
  Sarina,
  Schibsted_Grotesk,
  Share_Tech,
  Signika,
  Simonetta,
  Sora,
  Sorts_Mill_Goudy,
  Space_Mono,
  Spirax,
  Syne,
  Syne_Mono,
  Syne_Tactile,
  Tinos,
  Urbanist,
  Vidaloka,
  Wix_Madefor_Display,
  Xanh_Mono,
  Zen_Antique,
  Zen_Kaku_Gothic_New,
} from "next/font/google";

const abel = Abel({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-abel",
});
const akshar = Akshar({ subsets: ["latin"], display: "swap", variable: "--tl-face-akshar" });
const alfaSlabOne = Alfa_Slab_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-alfa-slab-one",
});
const allura = Allura({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-allura",
});
const amaticSc = Amatic_SC({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-amatic-sc",
});
const amiko = Amiko({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-amiko",
});
const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-anton",
});
const arsenal = Arsenal({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-arsenal",
});
const arvo = Arvo({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-arvo",
});
const asul = Asul({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-asul",
});
const averiaSerif = Averia_Serif_Libre({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-averia-serif",
});
const balthazar = Balthazar({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-balthazar",
});
const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-bebas-neue",
});
const bethEllen = Beth_Ellen({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-beth-ellen",
});
const biorhyme = BioRhyme({ subsets: ["latin"], display: "swap", variable: "--tl-face-biorhyme" });
const bitter = Bitter({ subsets: ["latin"], display: "swap", variable: "--tl-face-bitter" });
const blackHanSans = Black_Han_Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-black-han-sans",
});
const bookerly = Cherry_Swash({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-bookerly",
});
const cabin = Cabin({ subsets: ["latin"], display: "swap", variable: "--tl-face-cabin" });
const cormorant = Cormorant({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-cormorant",
});
const courierPrime = Courier_Prime({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-courier-prime",
});
const cousine = Cousine({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-cousine",
});
const coustard = Coustard({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-coustard",
});
const coveredByYourGrace = Covered_By_Your_Grace({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-covered-by-your-grace",
});
const crimson = Crimson_Text({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-crimson",
});
const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-crimson-pro",
});
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-dancing-script",
});
const dmSans = DM_Sans({ subsets: ["latin"], display: "swap", variable: "--tl-face-dm-sans" });
const domine = Domine({ subsets: ["latin"], display: "swap", variable: "--tl-face-domine" });
const dosis = Dosis({ subsets: ["latin"], display: "swap", variable: "--tl-face-dosis" });
const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-eb-garamond",
});
const fjalla = Fjalla_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-fjalla",
});
const frankRuhlLibre = Frank_Ruhl_Libre({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-frank-ruhl-libre",
});
const fraunces = Fraunces({ subsets: ["latin"], display: "swap", variable: "--tl-face-fraunces" });
const funnelDisplay = Funnel_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-funnel-display",
});
const funnelSans = Funnel_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-funnel-sans",
});
const fustat = Fustat({ subsets: ["latin"], display: "swap", variable: "--tl-face-fustat" });
const gantari = Gantari({ subsets: ["latin"], display: "swap", variable: "--tl-face-gantari" });
const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-geist-mono",
});
const geistSans = Geist({ subsets: ["latin"], display: "swap", variable: "--tl-face-geist-sans" });
const geologica = Geologica({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-geologica",
});
const germaniaOne = Germania_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-germania-one",
});
const gildaDisplay = Gilda_Display({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-gilda-display",
});
const glegoo = Glegoo({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-glegoo",
});
const gloock = Gloock({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-gloock",
});
const hinaMincho = Hina_Mincho({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-hina-mincho",
});
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-ibm-plex-sans",
});
const inclusiveSans = Inclusive_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-inclusive-sans",
});
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-instrument-sans",
});
const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-instrument-serif",
});
const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--tl-face-inter" });
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-josefin-sans",
});
const jost = Jost({ subsets: ["latin"], display: "swap", variable: "--tl-face-jost" });
const karla = Karla({ subsets: ["latin"], display: "swap", variable: "--tl-face-karla" });
const kiwiMaru = Kiwi_Maru({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-kiwi-maru",
});
const lato = Lato({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-lato",
});
const libreCaslonDisplay = Libre_Caslon_Display({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-libre-caslon-display",
});
const libreCaslonText = Libre_Caslon_Text({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-libre-caslon-text",
});
const lobster = Lobster({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-lobster",
});
const lora = Lora({ subsets: ["latin"], display: "swap", variable: "--tl-face-lora" });
const madimiOne = Madimi_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-madimi-one",
});
const manrope = Manrope({ subsets: ["latin"], display: "swap", variable: "--tl-face-manrope" });
const martianMono = Martian_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-martian-mono",
});
const merriweatherSans = Merriweather_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-merriweather-sans",
});
const metamorphous = Metamorphous({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-metamorphous",
});
const michroma = Michroma({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-michroma",
});
const miriamLibre = Miriam_Libre({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-miriam-libre",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-montserrat",
});
const newsreader = Newsreader({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-newsreader",
});
const notoNastaliqUrdu = Noto_Nastaliq_Urdu({
  subsets: ["arabic"],
  display: "swap",
  variable: "--tl-face-noto-nastaliq-urdu",
});
const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-noto-sans",
});
const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  display: "swap",
  variable: "--tl-face-noto-sans-arabic",
});
const notoSansEgyptianHieroglyphs = Noto_Sans_Egyptian_Hieroglyphs({
  subsets: ["egyptian-hieroglyphs"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-noto-sans-egyptian-hieroglyphs",
});
const notoSansLimbu = Noto_Sans_Limbu({
  subsets: ["limbu"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-noto-sans-limbu",
});
const notoSansMono = Noto_Sans_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-noto-sans-mono",
});
const notoSansSymbols = Noto_Sans_Symbols({
  subsets: ["symbols"],
  display: "swap",
  variable: "--tl-face-noto-sans-symbols",
});
const notoSansVai = Noto_Sans_Vai({
  subsets: ["vai"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-noto-sans-vai",
});
const notoSansWarangCiti = Noto_Sans_Warang_Citi({
  subsets: ["warang-citi"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-noto-sans-warang-citi",
});
const notoSerif = Noto_Serif({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-noto-serif",
});
const notoSerifTibetan = Noto_Serif_Tibetan({
  subsets: ["tibetan"],
  display: "swap",
  variable: "--tl-face-noto-serif-tibetan",
});
const novaSlim = Nova_Slim({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-nova-slim",
});
const nunito = Nunito({ subsets: ["latin"], display: "swap", variable: "--tl-face-nunito" });
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-nunito-sans",
});
const ojuju = Ojuju({ subsets: ["latin"], display: "swap", variable: "--tl-face-ojuju" });
const oldStandard = Old_Standard_TT({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-old-standard",
});
const orbitron = Orbitron({ subsets: ["latin"], display: "swap", variable: "--tl-face-orbitron" });
const outfit = Outfit({ subsets: ["latin"], display: "swap", variable: "--tl-face-outfit" });
const ovo = Ovo({ subsets: ["latin"], weight: "400", display: "swap", variable: "--tl-face-ovo" });
const pacificoVernonAdams = Pacifico({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-pacifico-vernon-adams",
});
const parkinsans = Parkinsans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-parkinsans",
});
const pinyonScript = Pinyon_Script({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-pinyon-script",
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-playfair-display",
});
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-plus-jakarta-sans",
});
const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-prompt",
});
const publicSans = Public_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-public-sans",
});
const quattrocento = Quattrocento({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-quattrocento",
});
const roboto = Roboto({ subsets: ["latin"], display: "swap", variable: "--tl-face-roboto" });
const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-roboto-condensed",
});
const rubik = Rubik({ subsets: ["latin"], display: "swap", variable: "--tl-face-rubik" });
const sarina = Sarina({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-sarina",
});
const schibstedGrotesk = Schibsted_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-schibsted-grotesk",
});
const shareTech = Share_Tech({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-share-tech",
});
const signika = Signika({ subsets: ["latin"], display: "swap", variable: "--tl-face-signika" });
const simonetta = Simonetta({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-simonetta",
});
const sora = Sora({ subsets: ["latin"], display: "swap", variable: "--tl-face-sora" });
const sortsMillGoudy = Sorts_Mill_Goudy({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-sorts-mill-goudy",
});
const sourceHanSans = Noto_Sans_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-source-han-sans",
});
const sourceHanSerif = Noto_Serif_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-source-han-serif",
});
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-space-mono",
});
const spirax = Spirax({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-spirax",
});
const syne = Syne({ subsets: ["latin"], display: "swap", variable: "--tl-face-syne" });
const syneMono = Syne_Mono({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-syne-mono",
});
const syneTactile = Syne_Tactile({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-syne-tactile",
});
const tinos = Tinos({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-tinos",
});
const urbanist = Urbanist({ subsets: ["latin"], display: "swap", variable: "--tl-face-urbanist" });
const vidaloka = Vidaloka({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-vidaloka",
});
const wixMadefor = Wix_Madefor_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--tl-face-wix-madefor",
});
const xanhMono = Xanh_Mono({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-xanh-mono",
});
const zenAntique = Zen_Antique({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-zen-antique",
});
const zenKakuGothicNew = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--tl-face-zen-kaku-gothic-new",
});

/** Every loaded face's `.variable` class. Apply once, on <html>. */
export const catalogFontClassName = [
  abel.variable,
  akshar.variable,
  alfaSlabOne.variable,
  allura.variable,
  amaticSc.variable,
  amiko.variable,
  anton.variable,
  arsenal.variable,
  arvo.variable,
  asul.variable,
  averiaSerif.variable,
  balthazar.variable,
  bebasNeue.variable,
  bethEllen.variable,
  biorhyme.variable,
  bitter.variable,
  blackHanSans.variable,
  bookerly.variable,
  cabin.variable,
  cormorant.variable,
  courierPrime.variable,
  cousine.variable,
  coustard.variable,
  coveredByYourGrace.variable,
  crimson.variable,
  crimsonPro.variable,
  dancingScript.variable,
  dmSans.variable,
  domine.variable,
  dosis.variable,
  ebGaramond.variable,
  fjalla.variable,
  frankRuhlLibre.variable,
  fraunces.variable,
  funnelDisplay.variable,
  funnelSans.variable,
  fustat.variable,
  gantari.variable,
  geistMono.variable,
  geistSans.variable,
  geologica.variable,
  germaniaOne.variable,
  gildaDisplay.variable,
  glegoo.variable,
  gloock.variable,
  hinaMincho.variable,
  ibmPlexSans.variable,
  inclusiveSans.variable,
  instrumentSans.variable,
  instrumentSerif.variable,
  inter.variable,
  josefinSans.variable,
  jost.variable,
  karla.variable,
  kiwiMaru.variable,
  lato.variable,
  libreCaslonDisplay.variable,
  libreCaslonText.variable,
  lobster.variable,
  lora.variable,
  madimiOne.variable,
  manrope.variable,
  martianMono.variable,
  merriweatherSans.variable,
  metamorphous.variable,
  michroma.variable,
  miriamLibre.variable,
  montserrat.variable,
  newsreader.variable,
  notoNastaliqUrdu.variable,
  notoSans.variable,
  notoSansArabic.variable,
  notoSansEgyptianHieroglyphs.variable,
  notoSansLimbu.variable,
  notoSansMono.variable,
  notoSansSymbols.variable,
  notoSansVai.variable,
  notoSansWarangCiti.variable,
  notoSerif.variable,
  notoSerifTibetan.variable,
  novaSlim.variable,
  nunito.variable,
  nunitoSans.variable,
  ojuju.variable,
  oldStandard.variable,
  orbitron.variable,
  outfit.variable,
  ovo.variable,
  pacificoVernonAdams.variable,
  parkinsans.variable,
  pinyonScript.variable,
  playfairDisplay.variable,
  plusJakartaSans.variable,
  prompt.variable,
  publicSans.variable,
  quattrocento.variable,
  roboto.variable,
  robotoCondensed.variable,
  rubik.variable,
  sarina.variable,
  schibstedGrotesk.variable,
  shareTech.variable,
  signika.variable,
  simonetta.variable,
  sora.variable,
  sortsMillGoudy.variable,
  sourceHanSans.variable,
  sourceHanSerif.variable,
  spaceMono.variable,
  spirax.variable,
  syne.variable,
  syneMono.variable,
  syneTactile.variable,
  tinos.variable,
  urbanist.variable,
  vidaloka.variable,
  wixMadefor.variable,
  xanhMono.variable,
  zenAntique.variable,
  zenKakuGothicNew.variable,
].join(" ");

/**
 * Typeface id → the CSS variable holding its self-hosted family.
 *
 * next/font reaches a face only through this variable; the bare family name in
 * `cssStack` matches nothing, which is why every specimen used to fall through
 * to the page font.
 */
export const CATALOG_FONT_VARS: Record<string, string> = {
  abel: "--tl-face-abel",
  akshar: "--tl-face-akshar",
  "alfa-slab-one": "--tl-face-alfa-slab-one",
  allura: "--tl-face-allura",
  "amatic-sc": "--tl-face-amatic-sc",
  amiko: "--tl-face-amiko",
  anton: "--tl-face-anton",
  arsenal: "--tl-face-arsenal",
  arvo: "--tl-face-arvo",
  asul: "--tl-face-asul",
  "averia-serif": "--tl-face-averia-serif",
  balthazar: "--tl-face-balthazar",
  "bebas-neue": "--tl-face-bebas-neue",
  "beth-ellen": "--tl-face-beth-ellen",
  biorhyme: "--tl-face-biorhyme",
  bitter: "--tl-face-bitter",
  "black-han-sans": "--tl-face-black-han-sans",
  bookerly: "--tl-face-bookerly",
  cabin: "--tl-face-cabin",
  cormorant: "--tl-face-cormorant",
  "courier-prime": "--tl-face-courier-prime",
  cousine: "--tl-face-cousine",
  coustard: "--tl-face-coustard",
  "covered-by-your-grace": "--tl-face-covered-by-your-grace",
  crimson: "--tl-face-crimson",
  "crimson-pro": "--tl-face-crimson-pro",
  "dancing-script": "--tl-face-dancing-script",
  "dm-sans": "--tl-face-dm-sans",
  domine: "--tl-face-domine",
  dosis: "--tl-face-dosis",
  "eb-garamond": "--tl-face-eb-garamond",
  fjalla: "--tl-face-fjalla",
  "frank-ruhl-libre": "--tl-face-frank-ruhl-libre",
  fraunces: "--tl-face-fraunces",
  "funnel-display": "--tl-face-funnel-display",
  "funnel-sans": "--tl-face-funnel-sans",
  fustat: "--tl-face-fustat",
  gantari: "--tl-face-gantari",
  "geist-mono": "--tl-face-geist-mono",
  "geist-sans": "--tl-face-geist-sans",
  geologica: "--tl-face-geologica",
  "germania-one": "--tl-face-germania-one",
  "gilda-display": "--tl-face-gilda-display",
  glegoo: "--tl-face-glegoo",
  gloock: "--tl-face-gloock",
  "hina-mincho": "--tl-face-hina-mincho",
  "ibm-plex-sans": "--tl-face-ibm-plex-sans",
  "inclusive-sans": "--tl-face-inclusive-sans",
  "instrument-sans": "--tl-face-instrument-sans",
  "instrument-serif": "--tl-face-instrument-serif",
  inter: "--tl-face-inter",
  "josefin-sans": "--tl-face-josefin-sans",
  jost: "--tl-face-jost",
  karla: "--tl-face-karla",
  "kiwi-maru": "--tl-face-kiwi-maru",
  lato: "--tl-face-lato",
  "libre-caslon-display": "--tl-face-libre-caslon-display",
  "libre-caslon-text": "--tl-face-libre-caslon-text",
  lobster: "--tl-face-lobster",
  lora: "--tl-face-lora",
  "madimi-one": "--tl-face-madimi-one",
  manrope: "--tl-face-manrope",
  "martian-mono": "--tl-face-martian-mono",
  "merriweather-sans": "--tl-face-merriweather-sans",
  metamorphous: "--tl-face-metamorphous",
  michroma: "--tl-face-michroma",
  "miriam-libre": "--tl-face-miriam-libre",
  montserrat: "--tl-face-montserrat",
  newsreader: "--tl-face-newsreader",
  "noto-nastaliq-urdu": "--tl-face-noto-nastaliq-urdu",
  "noto-sans": "--tl-face-noto-sans",
  "noto-sans-arabic": "--tl-face-noto-sans-arabic",
  "noto-sans-egyptian-hieroglyphs": "--tl-face-noto-sans-egyptian-hieroglyphs",
  "noto-sans-limbu": "--tl-face-noto-sans-limbu",
  "noto-sans-mono": "--tl-face-noto-sans-mono",
  "noto-sans-symbols": "--tl-face-noto-sans-symbols",
  "noto-sans-vai": "--tl-face-noto-sans-vai",
  "noto-sans-warang-citi": "--tl-face-noto-sans-warang-citi",
  "noto-serif": "--tl-face-noto-serif",
  "noto-serif-tibetan": "--tl-face-noto-serif-tibetan",
  "nova-slim": "--tl-face-nova-slim",
  nunito: "--tl-face-nunito",
  "nunito-sans": "--tl-face-nunito-sans",
  ojuju: "--tl-face-ojuju",
  "old-standard": "--tl-face-old-standard",
  orbitron: "--tl-face-orbitron",
  outfit: "--tl-face-outfit",
  ovo: "--tl-face-ovo",
  "pacifico-vernon-adams": "--tl-face-pacifico-vernon-adams",
  parkinsans: "--tl-face-parkinsans",
  "pinyon-script": "--tl-face-pinyon-script",
  "playfair-display": "--tl-face-playfair-display",
  "plus-jakarta-sans": "--tl-face-plus-jakarta-sans",
  prompt: "--tl-face-prompt",
  "public-sans": "--tl-face-public-sans",
  quattrocento: "--tl-face-quattrocento",
  roboto: "--tl-face-roboto",
  "roboto-condensed": "--tl-face-roboto-condensed",
  rubik: "--tl-face-rubik",
  sarina: "--tl-face-sarina",
  "schibsted-grotesk": "--tl-face-schibsted-grotesk",
  "share-tech": "--tl-face-share-tech",
  signika: "--tl-face-signika",
  simonetta: "--tl-face-simonetta",
  sora: "--tl-face-sora",
  "sorts-mill-goudy": "--tl-face-sorts-mill-goudy",
  "source-han-sans": "--tl-face-source-han-sans",
  "source-han-serif": "--tl-face-source-han-serif",
  "space-mono": "--tl-face-space-mono",
  spirax: "--tl-face-spirax",
  syne: "--tl-face-syne",
  "syne-mono": "--tl-face-syne-mono",
  "syne-tactile": "--tl-face-syne-tactile",
  tinos: "--tl-face-tinos",
  urbanist: "--tl-face-urbanist",
  vidaloka: "--tl-face-vidaloka",
  "wix-madefor": "--tl-face-wix-madefor",
  "xanh-mono": "--tl-face-xanh-mono",
  "zen-antique": "--tl-face-zen-antique",
  "zen-kaku-gothic-new": "--tl-face-zen-kaku-gothic-new",
};

/**
 * Faces Google does not carry. Surfaces should say so rather than render them
 * in a substitute — a specimen showing the wrong typeface is worse than one
 * that admits it has nothing to show.
 */
export const UNAVAILABLE_FACES: ReadonlySet<string> = new Set([
  "alwyn", // Alwyn
  "chachanika", // Chachanika
  "empathy", // Empathy
  "fucxed", // Fucxed
  "hagel-mono", // Hagel Mono
  "tt-russo-sans", // TT Russo Sans
  "tubi-stans", // Tubi Stans
  "wt-monarch", // WT Monarch
]);

/** Prepend the self-hosted family so the declared stack can actually resolve. */
export function resolvedStack(id: string, cssStack: string): string {
  const v = CATALOG_FONT_VARS[id];
  return v ? `var(${v}), ${cssStack}` : cssStack;
}
